(*
	The Haxe Compiler
	Copyright (C) 2005-2026  Haxe Foundation

	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with this program; if not, write to the Free Software
	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
*)

(*
	SA target (Safe ASM, 安全汇编).

	Emits SA text assembly (`.sa`) that feeds the `sci` toolchain
	(`sa build-exe` / `sa build-wasm`). All runtime calls lower to the
	canonical `sci/sa_std` contracts only (see `SA_TARGET.md`); this
	generator never invents new std APIs.

	Shape reference: `sala` help docs `content/03_sa_asm/02_sa_syntax.html`
	(minimal program, flat labels, explicit `!` releases) and
	`sci/demos/rosetta/01_hello_world/main.sa`.

	v0.1 status: skeleton. Emits a known-good SA shape (same instruction
	sequence as the `01_hello_world` rosetta demo) plus per-type comment
	stubs. Full texpr lowering (expressions, control flow, classes) is
	pending and tracked in `SA_TARGET.md`.
*)

open Globals
open Type
open Gctx

let sa_header = "\
// Generated by the Haxe SA target v0.1 (skeleton).\n\
// Full texpr lowering is pending, see SA_TARGET.md.\n\
// Shape reference: sci/demos/rosetta/01_hello_world/main.sa.\n"

let print_type buf mt =
	let comment =
		match mt with
		| TClassDecl c -> "// class " ^ (s_type_path c.cl_path)
		| TEnumDecl e -> "// enum " ^ (s_type_path e.e_path)
		| TTypeDecl t -> "// typedef " ^ (s_type_path t.t_path)
		| TAbstractDecl a -> "// abstract " ^ (s_type_path a.a_path)
	in
	Buffer.add_string buf comment;
	Buffer.add_char buf '\n'

let generate com =
	let buf = Buffer.create 1024 in
	Buffer.add_string buf sa_header;
	Buffer.add_string buf "@import \"sa_std/io/print.sai\"\n";
	Buffer.add_string buf "\n";
	Buffer.add_string buf "@const HAXE_SA_NOTE = utf8:\"haxe-sa v0.1 skeleton\\n\"\n";
	Buffer.add_string buf "\n";
	List.iter (print_type buf) com.types;
	Buffer.add_string buf "\n";
	Buffer.add_string buf "@main() -> i32:\n";
	Buffer.add_string buf "L_ENTRY:\n";
	Buffer.add_string buf "    call @sa_print_bytes(&HAXE_SA_NOTE, 22)\n";
	Buffer.add_string buf "    return 0\n";
	(match com.main.main_expr with
	| Some _ -> Buffer.add_string buf "// haxe main entry present (lowering pending)\n"
	| None -> Buffer.add_string buf "// no haxe main entry\n");
	let ch = open_out_bin com.file in
	output_string ch (Buffer.contents buf);
	close_out ch
